### ISSUE TITLE
Confuse doesn't fully support the XDG Base Directory specification

### ISSUE THREAD

**Issue by jrobeson** [sampsyo/confuse#29]
See https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

It should fall back to `$XDG_CONFIG_DIRS`  when there is no local config. It should likely also expose `$XDG_DATA_HOME`, but i'm not sure how

**Comment by sampsyo** [comment]
Can you elaborate a little more about what exactly Confuse should do with that environment variable? That will help make it clear what work needs to be done.

**Comment by jrobeson** [comment]
It should check if the files exist there,  so if `$XDG_CONFIG_DIRS` is set to `/usr/local/etc/xdg:/etc/xdg:`  then  it should search for the beets config there if it doesn't exist in `$XDG_CONFIG_HOME`

**Comment by sampsyo** [comment]
Aha—so it's just a list of directories that we should prepend to the search list. Sounds easy enough!
