### ISSUE TITLE
Option to include config file from project programmatically.

### ISSUE THREAD

**Issue by Toure** [sampsyo/confuse#30]
I really like this project first off, the one thing I think is missing is a method to pull in config.yml file for your current project. Example of what I am trying to convey:

Project path to config.yml
`Foo/config/config.yml`

> from Foo import config as cfg_path
>config = confuse.Configuration("Foo", cfg_path)

This I think would allow user the ability to work within the confines of the project without the
worries of setting enviornment variables, the problem this would solve is the reduction of boiler plate code to set environment varibles for various Unix distrobution ( Tru64 / Solaris ).
 
Thoughts?

**Comment by sampsyo** [comment]
Hi! I think I'm starting to see what you're getting at here, but is there any chance you could elaborate even more? To start with, what exactly do you mean by "project"—is that a Python package?

**Comment by Toure** [comment]
Hi Sampsyo, yeah sorry I have been a little more specific, "project" is equivlent to python package. I have had varying result when trying to use os.environ. So if the baseclass could take an additional argument for package path, I think that would simplify the inclusion of your project.

Thnaks.

**Comment by jackwilsdon** [comment]
Is there a reason this wouldn't work for you?

```Python
import os
from Foo import config as _config
import confuse

config = confuse.Configuration('Foo', read=False)  # Turn off `read` so that we don't try and read any other configurations.

# Work out the config file path by getting the path of `Foo.config` and then replace the last element with `config.yml`.
# This is the same as `os.path.join(os.path.dirname(__import__('Foo.config').__file__), 'config.yml')`.
config_path = os.path.join(__import__('Foo.config').__file__), os.pardir, 'config.yml')
config.set_file(config_path)  # We don't need to call `os.path.abspath` on the path as `confuse.Configuration#set_file` does it for us.
```

It's a bit long but I think it may be a better alternative?

**Comment by sampsyo** [comment]
Another possibility (which I'm not sure is appropriate for your use case) is to pass the appropriate module's name to the second argument of the `Configuration` constructor:

```py
import Foo.config
import confuse

config = confuse.Configuration('Foo', Foo.config.__name__)
```

The docs say the ordinary way is to use the `__name__` for the *current* module, but there's no reason you can't tell it too look elsewhere!

**Comment by jackwilsdon** [comment]
Much simpler than my solution @sampsyo. @Toure would have to rename their configuration from `config.yml` to `config.yaml` but apart from that it should work 😄.

**Comment by Toure** [comment]
@sampsyo @jackwilsdon Thanks for your help on this, I can now shed my use of ConfigParser forever 
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png)
