### ISSUE TITLE
Nested yaml element override via argparse

### ISSUE THREAD

**Issue by Toure** [sampsyo/confuse#32]
I have run into a limitaion or misconfiguration with confuse in regards to nested element lookup within a yaml file when using the following structure:

config.yaml

```YAML
logging:
  log_dir: '/tmp/foo'
```

config_test.py

```Python
config = confuse.Configuration('Cli_Test', config.__name__)
parser = argparse.ArgumentParser()
parser.add_argument("-lf", "--log_files", dest='log_dir', help="Path specified for log files.")
args = parser.parse_args()
config.set_args(args)
print(config['logging']['log_dir'].get())  # <-- confuse can not find the second level element.
```

Is this a known issue or did I mis-use the config object?

**Comment by sampsyo** [comment]
To set keys under a parent key, you should be able to just use:

```py
config['logging'].set_args(args)
# instead of:
# config.set_args(args)
```

Does that work here?

**Comment by Toure** [comment]
@sampsyo @jackwilsdon I tried the solution above and no joy.

> Traceback
> (most recent call last):
> File "cli.py", line 13, in <module>
>  print(config['log_dir'].get())
> File "/home/toure/Projects/PyCharm/iridium_test/lib/python3.4/site-packages/confuse.py", line 377, in get
> return as_template(template).value(self, template)
> File "/home/toure/Projects/PyCharm/iridium_test/lib/python3.4/site-packages/confuse.py", line 977, in value
>    raise NotFoundError(u"{0} not found".format(view.name))
> confuse.NotFoundError: log_dir not found

**Comment by sampsyo** [comment]
Can you please include the whole program that produced this traceback?

**Comment by elehcim** [comment]
For me it is working as @sampsyo suggested:
```
import confuse
import argparse

config = confuse.Configuration('Cli_Test')

config.set_file("config.yaml")  # <-- Did you add the correct config file?

parser = argparse.ArgumentParser()
parser.add_argument("-lf", "--log_files", dest='log_dir', help="Path specified for log files.")
args = parser.parse_args()
config["logging"].set_args(args)

print(config["logging"]['log_dir'].get())
```

    $ python config_test.py
    /tmp/foo
