### ISSUE TITLE
Optional template?

### ISSUE THREAD

**Issue by mavam** [sampsyo/confuse#45]
I've encountered this pattern where I'm having an optional configuration block:

```yaml
foo:
  x: false
  y: 42
```

In my template, I'm currently writing `confuse.OneOf([None, dict])`, but it's not really exactly right. This still requires `foo: null` in my config. What I want is an optional template where I can skip the definition of `foo` entirely. How would I do that?

**Comment by sampsyo** [comment]
Is the idea that both `x` and `y` are optional, or that they need to be specified together?

If the former, you can just access the individual fields, like `config['foo']['x'].get()`. Does that help at all?

**Comment by mavam** [comment]
Sorry if I wasn't clear, I used `x` and `y` only as dummy variables underneath `foo`. I was trying to figure out how to make `foo` optional, as opposed to `x` and `y`. So either the entire block should be there or it shouldn't matter if it's absent. Does that make sense? How would I describe that in a template?

**Comment by sampsyo** [comment]
I see! For the *non-optional* case, the right thing to use here is `MappingTemplate`—I assume you've tried that, right?

I think all that's needed to make the optional behavior work is to add a `default` option to `MappingTemplate`. If you take a look at the other `Template`s we have built in, such as `String` and `Choice`, you can see how that works. It may even be possible to get this behavior without modifying the Confuse source by assigning to the `default` field on the template "manually."

**Comment by mavam** [comment]
> I see! For the non-optional case, the right thing to use here is MappingTemplate—I assume you've tried that, right?

Actually, no. I tried to skim the example but couldn't find a usage example.

Here's what I was looking for:

```python
template = (
  'foo': confuse.Optional(dict)
)
```
If this existed, it would be okay to write a config with `foo` as dict or write a config without a `foo` key. That's what I'm trying to express. By using `confuse.OneOf([None, dict])`, I *have to* write `foo: null` in my config and cannot simply omit it. Otherwise `config = lazy_config.get(template)` will fail.

From a user perspective, I could now write `config.foo` and would know that it's either `None` or `dict`.

**Comment by sampsyo** [comment]
Indeed; it doesn't seem to be documented. Can I ask you the favor of forging ahead anyway, even if it means crossing into undocumented territory? Something like this should work:

```py
map_tmpl = confuse.MappingTemplate({'x': some_template, 'y': other_template})
map_tmpl.default = None
template = {'foo': map_tmpl}
```

**Comment by mavam** [comment]
Thanks, this was helpful. With a slight tweak, I have now exactly what I want:
```python
def optional(type):
    template = confuse.as_template(dict)
    template.default = None
    return template
```

This I can now use as follows:
```python
template = (
  'foo': optional({
    'x': optional(str),
    'y': optional(int),
  })
)
```

It's super flexible: not only top-level records can now be optional, but also fields within mappings.

If this use case is convincing enough for you, I would propose that `confuse.Optional` for that 😉. From my side, this issue is resolved.

**Comment by mavam** [comment]
Actually, it doesn't quite work as expected, because `foo` was still defined. This worked though:

```python
class OptionalMappingTemplate(confuse.MappingTemplate):
    def __init__(self, mapping):
        subtemplates = {}
        for key, typ in mapping.items():
            template = confuse.as_template(typ)
            template.default = None
            subtemplates[key] = template
        self.subtemplates = subtemplates
        self.default = None
    def value(self, view, template=None):
        out = confuse.AttrDict()
        for key, typ in self.subtemplates.items():
            x = typ.value(view[key], self)
            if x:
                out[key] = x
        return out if out else None

def optional(xs):
    return OptionalMappingTemplate(xs)
```

I really just hacked this together, there's probably a cleaner way to do it.

**Comment by sampsyo** [comment]
Aha! Yes, that looks a little more involved—but glad you figured it out!!
